#!/usr/bin/env python3
"""
Below The Line - Weekly Stock Data Pipeline

Fetches weekly price data from Yahoo Finance, calculates:
- 200-week moving average
- Distance from 200WMA (%)
- Week-over-week directional change
- 14-week RSI
- Historical touches of the 200WMA

Run weekly on Saturday to capture Friday close data.
"""
from __future__ import annotations

import json
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Optional, List

import pandas as pd
import yfinance as yf

# Configuration
OUTPUT_DIR = Path(__file__).parent.parent / 'assets' / 'data'
COMPANIES_FILE = OUTPUT_DIR / 'companies.json'

# Load company metadata
def load_company_metadata():
    """Load company names, sectors, and IR URLs from reference file."""
    if COMPANIES_FILE.exists():
        with open(COMPANIES_FILE) as f:
            return json.load(f)
    return {}

# Stock universe - Berkshire holdings + S&P 500 + Speculative/Growth

# Stock universe - 1,665 stocks (Full S&P 500, Mid-Cap, Small-Cap, Dividend, Growth)
STOCK_UNIVERSE = [
    'A',
    'AA',
    'AAL',
    'AAOI',
    'AAON',
    'AAP',
    'AAPL',
    'ABBV',
    'ABCB',
    'ABG',
    'ABM',
    'ABNB',
    'ABR',
    'ABT',
    'ACAD',
    'ACB',
    'ACCO',
    'ACGL',
    'ACHR',
    'ACLS',
    'ACM',
    'ACMR',
    'ACN',
    'ADBE',
    'ADC',
    'ADEA',
    'ADM',
    'ADMA',
    'ADNT',
    'ADP',
    'ADPT',
    'ADSK',
    'ADTN',
    'ADUS',
    'AEE',
    'AEIS',
    'AEO',
    'AEP',
    'AES',
    'AFG',
    'AFL',
    'AFRM',
    'AGCO',
    'AGNC',
    'AGO',
    'AHCO',
    'AHH',
    'AI',
    'AIG',
    'AIT',
    'AIZ',
    'AJG',
    'AKAM',
    'AKRO',
    'ALB',
    'ALE',
    'ALEC',
    'ALEX',
    'ALGM',
    'ALGN',
    'ALGT',
    'ALHC',
    'ALK',
    'ALKS',
    'ALL',
    'ALLE',
    'ALLO',
    'ALLY',
    'ALNY',
    'ALRM',
    'ALRS',
    'AM',
    'AMAT',
    'AMBA',
    'AMC',
    'AMCR',
    'AMD',
    'AME',
    'AMG',
    'AMGN',
    'AMKR',
    'AMP',
    'AMPH',
    'AMPL',
    'AMRC',
    'AMRK',
    'AMRX',
    'AMT',
    'AMWD',
    'AMZN',
    'ANAB',
    'ANDE',
    'ANET',
    'ANF',
    'ANIK',
    'ANIP',
    'ANSS',
    'AON',
    'AORT',
    'AOS',
    'AOSL',
    'APA',
    'APAM',
    'APD',
    'APEI',
    'APH',
    'APLD',
    'APLS',
    'APP',
    'APPF',
    'APPN',
    'APPS',
    'APTV',
    'AR',
    'ARAY',
    'ARCB',
    'ARCT',
    'ARDX',
    'ARE',
    'ARES',
    'ARHS',
    'ARKK',
    'ARLP',
    'ARM',
    'AROC',
    'AROW',
    'ARQT',
    'ARR',
    'ARRY',
    'ARTNA',
    'ARVN',
    'ARW',
    'ASB',
    'ASGN',
    'ASIX',
    'ASLE',
    'ASML',
    'ASPN',
    'ASTE',
    'ASTS',
    'ATEC',
    'ATEN',
    'ATHM',
    'ATI',
    'ATNI',
    'ATO',
    'ATRA',
    'ATRC',
    'ATRO',
    'AUB',
    'AVA',
    'AVAH',
    'AVAV',
    'AVB',
    'AVGO',
    'AVNS',
    'AVNW',
    'AVO',
    'AVPT',
    'AVTR',
    'AVY',
    'AWI',
    'AWK',
    'AWR',
    'AX',
    'AXGN',
    'AXON',
    'AXP',
    'AXS',
    'AXSM',
    'AXTA',
    'AXTI',
    'AYI',
    'AZN',
    'AZO',
    'AZZ',
    'B',
    'BA',
    'BABA',
    'BAC',
    'BALL',
    'BALY',
    'BANC',
    'BANF',
    'BANR',
    'BAX',
    'BBAI',
    'BBY',
    'BC',
    'BCC',
    'BCE',
    'BCML',
    'BCO',
    'BCPC',
    'BCRX',
    'BDC',
    'BDX',
    'BE',
    'BEAM',
    'BEN',
    'BF-B',
    'BG',
    'BGC',
    'BGS',
    'BHB',
    'BHE',
    'BHF',
    'BHP',
    'BHVN',
    'BIDU',
    'BIIB',
    'BILI',
    'BILL',
    'BIO',
    'BITF',
    'BITO',
    'BITX',
    'BJ',
    'BJRI',
    'BK',
    'BKD',
    'BKE',
    'BKH',
    'BKNG',
    'BKR',
    'BKSY',
    'BKU',
    'BL',
    'BLBD',
    'BLCO',
    'BLDR',
    'BLFS',
    'BLK',
    'BLKB',
    'BLMN',
    'BLNK',
    'BMBL',
    'BMI',
    'BMRC',
    'BMRN',
    'BMY',
    'BNL',
    'BNTX',
    'BOH',
    'BOKF',
    'BOOM',
    'BOOT',
    'BOX',
    'BP',
    'BPOP',
    'BR',
    'BRC',
    'BRCC',
    'BRK-B',
    'BRKR',
    'BRO',
    'BRSP',
    'BRX',
    'BRY',
    'BSM',
    'BSRR',
    'BSX',
    'BTAI',
    'BTDR',
    'BTG',
    'BTI',
    'BTU',
    'BURL',
    'BUSE',
    'BV',
    'BWA',
    'BWFG',
    'BWXT',
    'BX',
    'BXC',
    'BXMT',
    'BXP',
    'BY',
    'BYD',
    'BYND',
    'C',
    'CAC',
    'CACI',
    'CADE',
    'CAG',
    'CAH',
    'CAKE',
    'CALM',
    'CAMP',
    'CAR',
    'CARG',
    'CARR',
    'CASS',
    'CAT',
    'CATC',
    'CATO',
    'CATY',
    'CB',
    'CBAN',
    'CBFV',
    'CBL',
    'CBNK',
    'CBOE',
    'CBRE',
    'CBRL',
    'CBT',
    'CBU',
    'CBZ',
    'CCBG',
    'CCI',
    'CCJ',
    'CCL',
    'CCNE',
    'CCOI',
    'CCS',
    'CCSI',
    'CDNA',
    'CDNS',
    'CDRE',
    'CDW',
    'CDXS',
    'CE',
    'CECO',
    'CEG',
    'CELH',
    'CENT',
    'CENTA',
    'CENX',
    'CERS',
    'CERT',
    'CEVA',
    'CF',
    'CFG',
    'CFLT',
    'CFR',
    'CG',
    'CGC',
    'CGNX',
    'CHCT',
    'CHD',
    'CHDN',
    'CHE',
    'CHEF',
    'CHGG',
    'CHH',
    'CHPT',
    'CHRD',
    'CHRS',
    'CHRW',
    'CHTR',
    'CHWY',
    'CI',
    'CIEN',
    'CIFR',
    'CIGI',
    'CIM',
    'CINF',
    'CIVB',
    'CIVI',
    'CL',
    'CLB',
    'CLBK',
    'CLDT',
    'CLF',
    'CLFD',
    'CLH',
    'CLNE',
    'CLOV',
    'CLPR',
    'CLSK',
    'CLVT',
    'CLX',
    'CMA',
    'CMC',
    'CMCO',
    'CMCSA',
    'CME',
    'CMG',
    'CMI',
    'CMS',
    'CMT',
    'CNA',
    'CNC',
    'CNDT',
    'CNMD',
    'CNNE',
    'CNO',
    'CNOB',
    'CNP',
    'CNTY',
    'CNX',
    'CNXC',
    'COF',
    'COGT',
    'COHR',
    'COHU',
    'COIN',
    'COKE',
    'COLL',
    'COLM',
    'COMM',
    'COMP',
    'COO',
    'COP',
    'COR',
    'CORT',
    'CORZ',
    'COST',
    'COUR',
    'CPAY',
    'CPB',
    'CPK',
    'CPNG',
    'CPRT',
    'CPRX',
    'CPT',
    'CQP',
    'CR',
    'CRC',
    'CRI',
    'CRK',
    'CRL',
    'CRM',
    'CRMD',
    'CRMT',
    'CRNX',
    'CRON',
    'CROX',
    'CRS',
    'CRTO',
    'CRUS',
    'CRVL',
    'CRWD',
    'CSCO',
    'CSGP',
    'CSGS',
    'CSTL',
    'CSTM',
    'CSV',
    'CSWC',
    'CSX',
    'CTAS',
    'CTLT',
    'CTO',
    'CTRA',
    'CTSH',
    'CTVA',
    'CUBI',
    'CUK',
    'CURLF',
    'CUZ',
    'CVBF',
    'CVCO',
    'CVGI',
    'CVGW',
    'CVLG',
    'CVLT',
    'CVNA',
    'CVS',
    'CVX',
    'CW',
    'CWH',
    'CWST',
    'CXM',
    'CXW',
    'CYBR',
    'CYH',
    'CYRX',
    'CYTK',
    'CZR',
    'D',
    'DAKT',
    'DAL',
    'DAN',
    'DAR',
    'DAWN',
    'DAY',
    'DBD',
    'DBI',
    'DBX',
    'DCBO',
    'DCGO',
    'DCI',
    'DD',
    'DDD',
    'DDOG',
    'DDS',
    'DE',
    'DECK',
    'DELL',
    'DEO',
    'DFIN',
    'DFS',
    'DG',
    'DGII',
    'DGX',
    'DHC',
    'DHI',
    'DHR',
    'DHT',
    'DINO',
    'DIOD',
    'DIS',
    'DJT',
    'DKNG',
    'DKS',
    'DLB',
    'DLHC',
    'DLR',
    'DLTR',
    'DLX',
    'DNA',
    'DNLI',
    'DNN',
    'DNOW',
    'DNUT',
    'DOC',
    'DOCN',
    'DOCS',
    'DOCU',
    'DORM',
    'DOV',
    'DOW',
    'DOX',
    'DPZ',
    'DRH',
    'DRI',
    'DRVN',
    'DSGX',
    'DTE',
    'DUK',
    'DUOL',
    'DV',
    'DVA',
    'DVAX',
    'DVN',
    'DX',
    'DXC',
    'DXCM',
    'DY',
    'EA',
    'EAT',
    'EBAY',
    'EBC',
    'ECL',
    'ECPG',
    'ECVT',
    'ED',
    'EE',
    'EEFT',
    'EFSC',
    'EFX',
    'EG',
    'EGBN',
    'EGO',
    'EGP',
    'EHC',
    'EIX',
    'EL',
    'ELV',
    'EMBC',
    'EMN',
    'EMR',
    'ENB',
    'ENOV',
    'ENPH',
    'ENS',
    'ENSG',
    'ENTA',
    'ENTG',
    'ENVX',
    'EOG',
    'EPAC',
    'EPAM',
    'EPD',
    'EPM',
    'EPRT',
    'EQBK',
    'EQIX',
    'EQNR',
    'EQR',
    'EQT',
    'ERIE',
    'ERII',
    'ES',
    'ESCA',
    'ESI',
    'ESNT',
    'ESPR',
    'ESRT',
    'ESS',
    'ESTA',
    'ESTC',
    'ET',
    'ETD',
    'ETHE',
    'ETN',
    'ETR',
    'ETSY',
    'EVC',
    'EVER',
    'EVGO',
    'EVH',
    'EVLV',
    'EVR',
    'EVRG',
    'EVTC',
    'EW',
    'EWBC',
    'EXAS',
    'EXC',
    'EXEL',
    'EXLS',
    'EXP',
    'EXPD',
    'EXPE',
    'EXPI',
    'EXPO',
    'EXR',
    'EXTR',
    'F',
    'FAF',
    'FANG',
    'FAST',
    'FATE',
    'FBIN',
    'FBK',
    'FCEL',
    'FCNCA',
    'FCX',
    'FDS',
    'FDX',
    'FE',
    'FELE',
    'FFIN',
    'FFIV',
    'FHN',
    'FI',
    'FIBK',
    'FICO',
    'FIGS',
    'FIS',
    'FITB',
    'FIVE',
    'FIVN',
    'FIX',
    'FIZZ',
    'FLO',
    'FLWS',
    'FMBH',
    'FMC',
    'FMX',
    'FN',
    'FNB',
    'FND',
    'FNF',
    'FOLD',
    'FORM',
    'FORR',
    'FOUR',
    'FOX',
    'FOXA',
    'FOXF',
    'FRME',
    'FROG',
    'FRPT',
    'FRSH',
    'FRT',
    'FSLR',
    'FSLY',
    'FTI',
    'FTNT',
    'FTV',
    'FUL',
    'FUTU',
    'FWONK',
    'FWRD',
    'FWRG',
    'G',
    'GABC',
    'GATX',
    'GBCI',
    'GBTC',
    'GCO',
    'GD',
    'GDDY',
    'GDEN',
    'GDYN',
    'GE',
    'GEF',
    'GEHC',
    'GEN',
    'GENI',
    'GEO',
    'GERN',
    'GEV',
    'GEVO',
    'GFF',
    'GFS',
    'GGG',
    'GHC',
    'GIII',
    'GIL',
    'GILD',
    'GIS',
    'GL',
    'GLBE',
    'GLDD',
    'GLW',
    'GM',
    'GMAB',
    'GME',
    'GMRE',
    'GNRC',
    'GNTX',
    'GNW',
    'GO',
    'GOEV',
    'GOGO',
    'GOLF',
    'GOOD',
    'GOOG',
    'GOOGL',
    'GPC',
    'GPI',
    'GPK',
    'GPMT',
    'GPN',
    'GPRE',
    'GPRO',
    'GRAB',
    'GRBK',
    'GRC',
    'GRFS',
    'GRMN',
    'GRPN',
    'GRWG',
    'GS',
    'GSAT',
    'GSBC',
    'GSK',
    'GTBIF',
    'GTLB',
    'GVA',
    'GWW',
    'GXO',
    'H',
    'HAE',
    'HAFC',
    'HAIN',
    'HAL',
    'HALO',
    'HAS',
    'HASI',
    'HBAN',
    'HBB',
    'HBCP',
    'HBI',
    'HBM',
    'HBNC',
    'HBT',
    'HCA',
    'HCAT',
    'HCC',
    'HCI',
    'HCKT',
    'HCSG',
    'HD',
    'HDB',
    'HE',
    'HEI',
    'HEI-A',
    'HELE',
    'HES',
    'HGV',
    'HI',
    'HIFS',
    'HIG',
    'HII',
    'HL',
    'HLF',
    'HLI',
    'HLMN',
    'HLNE',
    'HLT',
    'HLX',
    'HMN',
    'HNI',
    'HOFT',
    'HOLX',
    'HOMB',
    'HON',
    'HOOD',
    'HOPE',
    'HOV',
    'HP',
    'HPE',
    'HPK',
    'HPQ',
    'HQI',
    'HQY',
    'HRI',
    'HRL',
    'HRMY',
    'HRTG',
    'HRTX',
    'HSIC',
    'HST',
    'HSTM',
    'HSY',
    'HTBK',
    'HTGC',
    'HTH',
    'HTLD',
    'HUBB',
    'HUBG',
    'HUBS',
    'HUM',
    'HUN',
    'HURN',
    'HUT',
    'HVT',
    'HWBK',
    'HWC',
    'HWKN',
    'HWM',
    'HXL',
    'HY',
    'HYLN',
    'HZO',
    'IAC',
    'IART',
    'IBCP',
    'IBEX',
    'IBIT',
    'IBKR',
    'IBM',
    'IBN',
    'IBOC',
    'IBP',
    'ICE',
    'ICFI',
    'ICHR',
    'ICLR',
    'ICUI',
    'IDCC',
    'IDT',
    'IDXX',
    'IESC',
    'IEX',
    'IFF',
    'IHG',
    'IHRT',
    'IIIV',
    'ILMN',
    'ILPT',
    'IMMR',
    'IMVT',
    'INBK',
    'INCY',
    'INDB',
    'INFU',
    'INFY',
    'ING',
    'INGR',
    'INO',
    'INOD',
    'INSG',
    'INSM',
    'INSP',
    'INSW',
    'INTA',
    'INTC',
    'INTU',
    'INVH',
    'IONQ',
    'IONS',
    'IOVA',
    'IP',
    'IPAR',
    'IPG',
    'IPGP',
    'IQ',
    'IQV',
    'IR',
    'IRBT',
    'IRDM',
    'IRM',
    'IRMD',
    'IRWD',
    'ISRG',
    'IT',
    'ITGR',
    'ITRI',
    'ITT',
    'ITUB',
    'ITW',
    'IVA',
    'IVR',
    'IVT',
    'IVZ',
    'IX',
    'J',
    'JACK',
    'JAMF',
    'JAZZ',
    'JBGS',
    'JBHT',
    'JBI',
    'JBL',
    'JBLU',
    'JBSS',
    'JCI',
    'JD',
    'JEF',
    'JELD',
    'JHG',
    'JJSF',
    'JKHY',
    'JKS',
    'JLL',
    'JNJ',
    'JNPR',
    'JOBY',
    'JOE',
    'JPM',
    'K',
    'KAI',
    'KALU',
    'KAR',
    'KB',
    'KBH',
    'KBR',
    'KDP',
    'KE',
    'KEX',
    'KEY',
    'KEYS',
    'KFRC',
    'KFY',
    'KGS',
    'KHC',
    'KIM',
    'KKR',
    'KLAC',
    'KLIC',
    'KMB',
    'KMI',
    'KMT',
    'KMX',
    'KN',
    'KNSA',
    'KNSL',
    'KNX',
    'KO',
    'KOD',
    'KOS',
    'KR',
    'KRC',
    'KREF',
    'KRG',
    'KROS',
    'KRP',
    'KRUS',
    'KRYS',
    'KSS',
    'KTOS',
    'KURA',
    'KVUE',
    'KVYO',
    'KW',
    'KWR',
    'KYMR',
    'L',
    'LADR',
    'LAKE',
    'LAMR',
    'LAND',
    'LASR',
    'LAUR',
    'LAW',
    'LAZ',
    'LAZR',
    'LB',
    'LBRDA',
    'LBRDK',
    'LBRT',
    'LC',
    'LCID',
    'LCII',
    'LCNB',
    'LCUT',
    'LDI',
    'LDOS',
    'LE',
    'LEA',
    'LEG',
    'LEGH',
    'LEN',
    'LESL',
    'LEU',
    'LFMD',
    'LFST',
    'LFUS',
    'LGIH',
    'LGND',
    'LH',
    'LHX',
    'LI',
    'LII',
    'LIN',
    'LIND',
    'LITE',
    'LIVN',
    'LKFN',
    'LKQ',
    'LLY',
    'LMAT',
    'LMND',
    'LMNR',
    'LMT',
    'LNC',
    'LNG',
    'LNN',
    'LNT',
    'LNTH',
    'LNZA',
    'LOB',
    'LOCO',
    'LOGI',
    'LOOP',
    'LOPE',
    'LOVE',
    'LOW',
    'LPLA',
    'LPX',
    'LRCX',
    'LSCC',
    'LSPD',
    'LSTR',
    'LTC',
    'LULU',
    'LUMN',
    'LUNA',
    'LUNG',
    'LUNR',
    'LUV',
    'LVS',
    'LW',
    'LXRX',
    'LXU',
    'LYB',
    'LYV',
    'LZB',
    'M',
    'MA',
    'MAA',
    'MAIN',
    'MANH',
    'MAR',
    'MARA',
    'MAS',
    'MASI',
    'MAT',
    'MATV',
    'MATW',
    'MATX',
    'MAX',
    'MAXN',
    'MBC',
    'MBCN',
    'MBIN',
    'MBUU',
    'MBWM',
    'MC',
    'MCB',
    'MCBS',
    'MCD',
    'MCFT',
    'MCHP',
    'MCK',
    'MCO',
    'MCRI',
    'MCW',
    'MCY',
    'MDB',
    'MDGL',
    'MDLZ',
    'MDRX',
    'MDT',
    'MDU',
    'MDXG',
    'MEDP',
    'MEG',
    'MEI',
    'MELI',
    'MET',
    'META',
    'MFA',
    'MG',
    'MGEE',
    'MGM',
    'MGNI',
    'MGNX',
    'MGPI',
    'MGTX',
    'MHK',
    'MHO',
    'MIDD',
    'MIND',
    'MIRM',
    'MITK',
    'MKC',
    'MKSI',
    'MKTX',
    'MLCO',
    'MLI',
    'MLM',
    'MLR',
    'MMC',
    'MMM',
    'MMSI',
    'MNKD',
    'MNR',
    'MNRO',
    'MNST',
    'MNTK',
    'MNTS',
    'MO',
    'MOD',
    'MOFG',
    'MOH',
    'MOS',
    'MOV',
    'MPAA',
    'MPB',
    'MPC',
    'MPLX',
    'MPW',
    'MPWR',
    'MQ',
    'MRCY',
    'MRK',
    'MRM',
    'MRNA',
    'MRO',
    'MRSN',
    'MRTN',
    'MRUS',
    'MRVI',
    'MRVL',
    'MS',
    'MSA',
    'MSBI',
    'MSCI',
    'MSEX',
    'MSFT',
    'MSGE',
    'MSGS',
    'MSI',
    'MSM',
    'MSTR',
    'MSTU',
    'MT',
    'MTB',
    'MTCH',
    'MTD',
    'MTDR',
    'MTG',
    'MTH',
    'MTLS',
    'MTN',
    'MTRN',
    'MTSI',
    'MTX',
    'MU',
    'MUFG',
    'MUR',
    'MUSA',
    'MUX',
    'MVBF',
    'MVST',
    'MWA',
    'MXCT',
    'MXL',
    'MYE',
    'MYFW',
    'MYGN',
    'MYRG',
    'NABL',
    'NATH',
    'NATR',
    'NAVI',
    'NBHC',
    'NBIS',
    'NBIX',
    'NBN',
    'NBR',
    'NBTB',
    'NCLH',
    'NCMI',
    'NCNO',
    'NCSM',
    'NDAQ',
    'NDLS',
    'NDSN',
    'NE',
    'NEE',
    'NEM',
    'NEOG',
    'NEON',
    'NESR',
    'NET',
    'NEU',
    'NEWT',
    'NEXT',
    'NFBK',
    'NFE',
    'NFG',
    'NFLX',
    'NG',
    'NGD',
    'NGS',
    'NGVC',
    'NGVT',
    'NHC',
    'NHI',
    'NI',
    'NICE',
    'NIO',
    'NJR',
    'NKE',
    'NL',
    'NLY',
    'NMFC',
    'NMIH',
    'NMM',
    'NMRA',
    'NMRK',
    'NNI',
    'NNN',
    'NOC',
    'NODK',
    'NOG',
    'NOK',
    'NOV',
    'NOVT',
    'NOW',
    'NPK',
    'NPO',
    'NRC',
    'NRDS',
    'NREF',
    'NRG',
    'NRIM',
    'NRIX',
    'NSA',
    'NSC',
    'NSIT',
    'NSP',
    'NSSC',
    'NTAP',
    'NTCT',
    'NTES',
    'NTGR',
    'NTIC',
    'NTLA',
    'NTNX',
    'NTRA',
    'NTRS',
    'NTST',
    'NU',
    'NUE',
    'NUS',
    'NUVB',
    'NVAX',
    'NVCR',
    'NVDA',
    'NVEC',
    'NVGS',
    'NVO',
    'NVR',
    'NVS',
    'NVST',
    'NVT',
    'NWBI',
    'NWE',
    'NWFL',
    'NWL',
    'NWN',
    'NWPX',
    'NWS',
    'NWSA',
    'NX',
    'NXPI',
    'NXRT',
    'NXST',
    'NXTC',
    'NYT',
    'O',
    'OBT',
    'OC',
    'OCFC',
    'OCGN',
    'OCSL',
    'OCUL',
    'ODC',
    'ODFL',
    'ODP',
    'OEC',
    'OFG',
    'OFIX',
    'OFLX',
    'OGE',
    'OGI',
    'OGN',
    'OGS',
    'OHI',
    'OI',
    'OII',
    'OIS',
    'OKE',
    'OKTA',
    'OLLI',
    'OLN',
    'OLP',
    'OM',
    'OMC',
    'OMCL',
    'OMER',
    'OMF',
    'OMI',
    'ON',
    'ONB',
    'ONEW',
    'ONTO',
    'OPBK',
    'OPEN',
    'OPFI',
    'OPK',
    'OPRA',
    'OPRT',
    'OPY',
    'ORA',
    'ORC',
    'ORCL',
    'ORGO',
    'ORI',
    'ORIC',
    'ORLA',
    'ORLY',
    'ORN',
    'ORRF',
    'OSIS',
    'OSK',
    'OSPN',
    'OSUR',
    'OSW',
    'OTIS',
    'OTLY',
    'OTTR',
    'OUST',
    'OUT',
    'OVBC',
    'OVV',
    'OWL',
    'OXM',
    'OXY',
    'OZK',
    'PAA',
    'PAAS',
    'PAC',
    'PACB',
    'PACK',
    'PAG',
    'PAGP',
    'PAGS',
    'PAHC',
    'PANW',
    'PAR',
    'PARA',
    'PARR',
    'PATH',
    'PATK',
    'PAYC',
    'PAYS',
    'PAYX',
    'PB',
    'PBA',
    'PBF',
    'PBFS',
    'PBH',
    'PBI',
    'PBR',
    'PCAR',
    'PCB',
    'PCG',
    'PCH',
    'PCOR',
    'PCRX',
    'PCTY',
    'PCVX',
    'PD',
    'PDD',
    'PEG',
    'PENN',
    'PEP',
    'PFE',
    'PFG',
    'PFGC',
    'PG',
    'PGR',
    'PH',
    'PHM',
    'PINS',
    'PKG',
    'PL',
    'PLD',
    'PLTR',
    'PLUG',
    'PM',
    'PNC',
    'PNFP',
    'PNR',
    'PNW',
    'PODD',
    'POOL',
    'POWI',
    'PPG',
    'PPL',
    'PR',
    'PRI',
    'PRTA',
    'PRU',
    'PSA',
    'PSX',
    'PTC',
    'PTON',
    'PUBM',
    'PWR',
    'PXD',
    'PYPL',
    'QBTS',
    'QCOM',
    'QLYS',
    'QRVO',
    'QS',
    'QUBT',
    'RARE',
    'RBC',
    'RBLX',
    'RCAT',
    'RCL',
    'RDDT',
    'RDW',
    'REG',
    'REGN',
    'RF',
    'RGTI',
    'RH',
    'RIO',
    'RIOT',
    'RITM',
    'RIVN',
    'RJF',
    'RKLB',
    'RL',
    'RLI',
    'RMD',
    'RNG',
    'ROK',
    'ROKU',
    'ROL',
    'ROOT',
    'ROP',
    'ROST',
    'RPD',
    'RRC',
    'RRX',
    'RS',
    'RSG',
    'RSI',
    'RTX',
    'RUN',
    'RVLV',
    'S',
    'SAIC',
    'SAN',
    'SAP',
    'SBAC',
    'SBCF',
    'SBUX',
    'SCHD',
    'SCHW',
    'SE',
    'SEDG',
    'SEIC',
    'SFNC',
    'SHEL',
    'SHG',
    'SHOP',
    'SHW',
    'SIRI',
    'SITE',
    'SJM',
    'SLB',
    'SLDP',
    'SMCI',
    'SMFG',
    'SMR',
    'SMTC',
    'SNA',
    'SNAP',
    'SNDL',
    'SNOW',
    'SNPS',
    'SNV',
    'SNY',
    'SO',
    'SOFI',
    'SOLV',
    'SONY',
    'SOUN',
    'SPCE',
    'SPG',
    'SPGI',
    'SPOT',
    'SRE',
    'SRPT',
    'SSB',
    'STE',
    'STEM',
    'STLD',
    'STT',
    'STX',
    'STZ',
    'SWK',
    'SWKS',
    'SYF',
    'SYK',
    'SYNA',
    'SYY',
    'T',
    'TAP',
    'TCBI',
    'TCOM',
    'TDG',
    'TDY',
    'TEAM',
    'TECH',
    'TEL',
    'TEM',
    'TENB',
    'TER',
    'TEVA',
    'TFC',
    'TFX',
    'TGT',
    'TGTX',
    'TIGR',
    'TJX',
    'TLRY',
    'TM',
    'TME',
    'TMO',
    'TMUS',
    'TOL',
    'TPR',
    'TRGP',
    'TRIP',
    'TRMB',
    'TROW',
    'TRV',
    'TSCO',
    'TSLA',
    'TSM',
    'TSN',
    'TT',
    'TTC',
    'TTD',
    'TTE',
    'TTWO',
    'TWLO',
    'TXN',
    'TXT',
    'TYL',
    'U',
    'UAL',
    'UBER',
    'UBSI',
    'UDR',
    'UHS',
    'UL',
    'ULTA',
    'UNH',
    'UNP',
    'UPS',
    'UPST',
    'URBN',
    'URI',
    'USB',
    'USFD',
    'UTHR',
    'UUUU',
    'V',
    'VALE',
    'VEEV',
    'VICI',
    'VLO',
    'VLTO',
    'VMC',
    'VNDA',
    'VRNS',
    'VRSK',
    'VRSN',
    'VRT',
    'VRTX',
    'VST',
    'VTR',
    'VTRS',
    'VXRT',
    'VZ',
    'W',
    'WAB',
    'WAL',
    'WAT',
    'WBA',
    'WBD',
    'WCC',
    'WDAY',
    'WDC',
    'WEC',
    'WELL',
    'WFC',
    'WH',
    'WIT',
    'WK',
    'WKHS',
    'WLK',
    'WM',
    'WMB',
    'WMT',
    'WRB',
    'WRK',
    'WSM',
    'WST',
    'WTFC',
    'WTW',
    'WULF',
    'WWD',
    'WY',
    'WYNN',
    'XEL',
    'XENE',
    'XOM',
    'XPEV',
    'XYL',
    'YUM',
    'Z',
    'ZBH',
    'ZBRA',
    'ZION',
    'ZS',
    'ZTS',
    'ZWS',
]

def fetch_weekly_data(symbol: str) -> Optional[pd.DataFrame]:
    """
    Fetch weekly price data from Yahoo Finance.
    
    Returns DataFrame with columns: Open, High, Low, Close, Volume
    """
    try:
        ticker = yf.Ticker(symbol)
        df = ticker.history(period="max", interval="1wk")
        
        if df.empty:
            print(f"  ✗ No data returned for {symbol}")
            return None
        
        # Rename columns for consistency
        df = df.rename(columns={
            'Open': 'open',
            'High': 'high',
            'Low': 'low',
            'Close': 'close',
            'Volume': 'volume'
        })
        
        # Use Close as adjusted_close (yfinance already adjusts by default)
        df['adjusted_close'] = df['close']
        
        return df
        
    except Exception as e:
        print(f"  ✗ Error fetching {symbol}: {e}")
        return None


def calculate_rsi(prices: pd.Series, periods: int = 14) -> pd.Series:
    """
    Calculate RSI (Relative Strength Index).
    
    14-week RSI on weekly data:
    - < 30: Oversold (potential buying opportunity)
    - < 20: Extremely oversold
    - > 70: Overbought
    """
    delta = prices.diff()
    
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    avg_gain = gain.rolling(window=periods).mean()
    avg_loss = loss.rolling(window=periods).mean()
    
    # Avoid division by zero
    rs = avg_gain / avg_loss.replace(0, float('inf'))
    rsi = 100 - (100 / (1 + rs))
    
    return rsi


def find_historical_touches(df: pd.DataFrame) -> List[dict]:
    """
    Find all periods where stock crossed below 200WMA.
    
    Returns list of touch events with:
    - Start date
    - Duration (weeks below)
    - Maximum depth below line
    - Return 1 year after crossing back above
    """
    touches = []
    
    # Identify cross-below events
    df = df.copy()
    df['below_line'] = df['adjusted_close'] < df['WMA_200']
    df['cross_below'] = (df['below_line']) & (~df['below_line'].shift(1).fillna(False).astype(bool))
    
    cross_dates = df[df['cross_below']].index.tolist()
    
    for cross_date in cross_dates:
        # Find when it crossed back above
        subsequent = df[df.index > cross_date]
        cross_above = subsequent[~subsequent['below_line']]
        
        if len(cross_above) > 0:
            recovery_date = cross_above.index[0]
            
            # Calculate weeks below
            period_below = df[(df.index >= cross_date) & (df.index < recovery_date)]
            weeks_below = len(period_below)
            
            # Calculate max depth below line during this period
            max_depth = period_below['pct_from_wma'].min()
            
            # Calculate 1-year return from recovery date
            one_year_later = recovery_date + pd.DateOffset(weeks=52)
            if one_year_later <= df.index[-1]:
                recovery_price = df.loc[recovery_date, 'adjusted_close']
                future_data = df[df.index >= one_year_later]
                if len(future_data) > 0:
                    future_price = future_data.iloc[0]['adjusted_close']
                    one_year_return = ((future_price - recovery_price) / recovery_price) * 100
                else:
                    one_year_return = None
            else:
                one_year_return = None
            
            touches.append({
                'date': cross_date.strftime('%b %Y'),
                'date_iso': cross_date.strftime('%Y-%m-%d'),
                'weeks_below': int(weeks_below),
                'max_depth': round(float(max_depth), 1),
                'return_1yr': round(float(one_year_return), 1) if one_year_return is not None else None
            })
        else:
            # Currently still below the line
            period_below = df[df.index >= cross_date]
            weeks_below = len(period_below)
            max_depth = period_below['pct_from_wma'].min()
            
            touches.append({
                'date': cross_date.strftime('%b %Y'),
                'date_iso': cross_date.strftime('%Y-%m-%d'),
                'weeks_below': int(weeks_below),
                'max_depth': round(float(max_depth), 1),
                'return_1yr': None,
                'ongoing': True
            })
    
    return touches


def calculate_stock_signals(symbol: str) -> Optional[dict]:
    """
    Calculate all signals for a stock.
    
    Returns dict with:
    - symbol, close, wma_200
    - pct_from_wma (distance from 200WMA)
    - wow_change (week-over-week directional change)
    - rsi_14 (14-week RSI)
    - below_line (boolean)
    - approaching (boolean - moving toward the line)
    - historical_touches (list of past touches)
    """
    print(f"  Processing {symbol}...")
    
    df = fetch_weekly_data(symbol)
    if df is None:
        return None
    
    if len(df) < 200:
        print(f"  ✗ {symbol}: Only {len(df)} weeks of data (need 200+)")
        # Still process stocks with less data, just won't have full 200WMA history
        if len(df) < 50:
            return None
    
    # === 200-WEEK MOVING AVERAGE ===
    df['WMA_200'] = df['adjusted_close'].rolling(window=200, min_periods=50).mean()
    
    # === DISTANCE FROM 200WMA ===
    df['pct_from_wma'] = ((df['adjusted_close'] - df['WMA_200']) / df['WMA_200']) * 100
    
    # === WEEK-OVER-WEEK DIRECTIONAL CHANGE ===
    df['wow_change'] = df['pct_from_wma'] - df['pct_from_wma'].shift(1)
    
    # === 14-WEEK RSI ===
    df['RSI_14'] = calculate_rsi(df['adjusted_close'], periods=14)
    
    # === HISTORICAL TOUCHES ===
    df_complete = df.dropna(subset=['WMA_200'])
    if len(df_complete) == 0:
        print(f"  ✗ {symbol}: No valid WMA data")
        return None
    
    historical_touches = find_historical_touches(df_complete.copy())
    
    # Get latest values
    latest = df_complete.iloc[-1]
    
    # Calculate buy threshold (the 200WMA value)
    buy_threshold = latest['WMA_200']
    
    # Determine signal color zone
    pct = latest['pct_from_wma']
    if pct <= -10:
        zone = 'extreme_value'
    elif pct <= -5:
        zone = 'deep_value'
    elif pct <= 0:
        zone = 'below_line'
    elif pct <= 5:
        zone = 'at_doorstep'
    elif pct <= 10:
        zone = 'getting_close'
    elif pct <= 15:
        zone = 'approaching'
    else:
        zone = 'above'
    
    # Calculate average return from historical touches
    returns = [t['return_1yr'] for t in historical_touches if t.get('return_1yr') is not None]
    avg_return = round(sum(returns) / len(returns), 1) if returns else None
    avg_weeks = round(sum(t['weeks_below'] for t in historical_touches) / len(historical_touches), 1) if historical_touches else None
    
    result = {
        'symbol': symbol,
        'close': round(float(latest['adjusted_close']), 2),
        'wma_200': round(float(latest['WMA_200']), 2),
        'buy_threshold': round(float(buy_threshold), 2),
        'pct_from_wma': round(float(latest['pct_from_wma']), 2),
        'wow_change': round(float(latest['wow_change']), 2) if pd.notna(latest['wow_change']) else 0.0,
        'rsi_14': round(float(latest['RSI_14']), 1) if pd.notna(latest['RSI_14']) else 50.0,
        'below_line': bool(latest['adjusted_close'] < latest['WMA_200']),
        'approaching': float(latest['wow_change']) < 0 if pd.notna(latest['wow_change']) else False,
        'zone': zone,
        'historical_touches': historical_touches,
        'touch_count': len(historical_touches),
        'avg_return_after_touch': avg_return,
        'avg_weeks_below': avg_weeks,
        'last_updated': df_complete.index[-1].strftime('%Y-%m-%d'),
        'data_weeks': len(df_complete)
    }
    
    print(f"  ✓ {symbol}: {pct:.1f}% from WMA, RSI: {latest['RSI_14']:.0f}, Zone: {zone}")
    return result


def generate_landing_page_data(stocks: List[dict]) -> dict:
    """
    Generate summary data for the landing page.
    """
    below_line = [s for s in stocks if s['below_line']]
    approaching = [s for s in stocks if not s['below_line'] and s['zone'] in ['at_doorstep', 'getting_close', 'approaching']]
    oversold = [s for s in stocks if s['rsi_14'] < 30]
    
    # Sort by closest to line
    approaching_sorted = sorted(approaching, key=lambda x: x['pct_from_wma'])
    below_sorted = sorted(below_line, key=lambda x: x['pct_from_wma'])
    
    return {
        'total_stocks': len(stocks),
        'below_line_count': len(below_line),
        'approaching_count': len(approaching),
        'oversold_count': len(oversold),
        'below_line_stocks': below_sorted,
        'approaching_stocks': approaching_sorted[:10],
        'oversold_stocks': [s for s in stocks if s['rsi_14'] < 30],
    }


def main():
    """Main entry point for weekly data update."""
    print("=" * 60)
    print("Below The Line - Weekly Data Update (Yahoo Finance)")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # Load company metadata
    companies = load_company_metadata()
    print(f"Loaded metadata for {len(companies)} companies")
    
    results = []
    errors = []
    
    print(f"\nProcessing {len(STOCK_UNIVERSE)} stocks...")
    print("-" * 60)
    
    for i, symbol in enumerate(STOCK_UNIVERSE):
        data = calculate_stock_signals(symbol)
        
        if data:
            # Merge company metadata
            if symbol in companies:
                data['name'] = companies[symbol].get('name', symbol)
                data['sector'] = companies[symbol].get('sector', '')
                data['ir_url'] = companies[symbol].get('ir_url', '')
            else:
                data['name'] = symbol
                data['sector'] = ''
                data['ir_url'] = ''
            
            results.append(data)
        else:
            errors.append(symbol)
        
        # Small delay to be respectful to Yahoo Finance
        if i % 50 == 0 and i > 0:
            print(f"  ... processed {i}/{len(STOCK_UNIVERSE)} stocks")
            time.sleep(1)
    
    print("-" * 60)
    print(f"Successfully processed: {len(results)}/{len(STOCK_UNIVERSE)}")
    if errors:
        print(f"Errors ({len(errors)}): {', '.join(errors[:20])}")
        if len(errors) > 20:
            print(f"  ... and {len(errors) - 20} more")
    
    # Generate output
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Individual stock data
    output = {
        'stocks': results,
        'summary': generate_landing_page_data(results),
        'generated': datetime.now().isoformat(),
        'generated_readable': datetime.now().strftime('%B %d, %Y')
    }
    
    output_file = OUTPUT_DIR / 'stocks.json'
    with open(output_file, 'w') as f:
        json.dump(output, f, indent=2)
    
    print(f"\nOutput written to: {output_file}")
    print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)


if __name__ == '__main__':
    main()
